---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraform-service
  namespace: keptn
  labels:
    app.kubernetes.io/name: terraform-service
    app.kubernetes.io/instance: keptn
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: control-plane
    app.kubernetes.io/version: develop
spec:
  selector:
    matchLabels:
      run: terraform-service
  replicas: 1
  template:
    metadata:
      labels:
        run: terraform-service
        app.kubernetes.io/name: terraform-service
        app.kubernetes.io/instance: keptn
        app.kubernetes.io/part-of: keptn-keptn
        app.kubernetes.io/component: control-plane
        app.kubernetes.io/version: develop
    spec:
      containers:
        - name: terraform-service
          image: bradmccoydev/terraform-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: CONFIGURATION_SERVICE
              value: 'http://configuration-service:8080'
        - name: distributor
          image: keptn/distributor:0.11.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "16Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.>'
            - name: PUBSUB_RECIPIENT
              value: '127.0.0.1'
            - name: VERSION
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: 'metadata.labels[''app.kubernetes.io/version'']'
            - name: K8S_DEPLOYMENT_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: 'metadata.labels[''app.kubernetes.io/name'']'
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
      serviceAccountName: keptn-default
---
apiVersion: v1
kind: Service
metadata:
  name: terraform-service
  namespace: keptn
  labels:
    run: terraform-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: terraform-service

